### ISSUE TITLE
Add ability to specify base branch

### ISSUE THREAD

**Issue by tknerr** [mikestead/bitbucket-changelog#3]
Currently `bbgenlog` only looks for PRs being merged to "master"

We use a different branching model and would be interested in PRs merged to "develop".

For other projects we have to maintain a "release/1.x" branch, and would love to be able to generate a changelog for these as well.

It would be awesome if the base branch could be passed as a cmdline parameter for these scenarios

**Comment by mikestead** [comment]
Fixed by #5
