### ISSUE TITLE
<small> is not working on Bitbucket Server?

### ISSUE THREAD

**Issue by tknerr** [mikestead/bitbucket-changelog#6]
I'm wondering about the usage of the `<small>` tag in the generated markdown output.

Our Bitbucket Server instance (v5.4.0) does not seem to render this. Does it work for you?

I'm wondering if there is a more cross-compatible markdownish way of having this...

**Comment by tknerr** [comment]
Bitbucket server does not support any of either <sub>subscript</sub> or <sup>superscript</sup> or <small>small</small>... :-/

verbatim:
```
Bitbucket server does not support any of either <sub>subscript</sub> or <sup>superscript</sup> or <small>small</small>... :-/
```

**Comment by mikestead** [comment]
@tknerr Interesting, where did you spot that one? It's rendering the `<small>` html tag ok for us and the browser (given the Bitbucket server styesheets) then renders it a fraction smaller (`12px` vs `14px`). We're using 5.2.2.

**Comment by tknerr** [comment]
Weird. This is how it looks like on our Bitbucket server v5.4.0 and using latest Chrome browser:

![image](https://user-images.githubusercontent.com/365744/33114999-a0429f6a-cf5f-11e7-9065-41ebc353acb0.png)

The raw source file looks good too, i.e. no escaping of html tags or whatsoever...

Might be that we have some kind of odd configuration of safe rendering option in our bitbucket server configured? no idea...

**Comment by tknerr** [comment]
Sounds a lot like this issue:
https://jira.atlassian.com/browse/BSERV-10202

**Comment by tknerr** [comment]
this is working with Bitbucket Server 5.5.1 again...
