### ISSUE TITLE
Add anchor element above version number in changelog

### ISSUE THREAD

**Issue by engfragui** [mikestead/bitbucket-changelog#8]
I think it would be beneficial to add an anchor element above the version number in the changelog.

Currently:
```
## 1.0.0
Feb 28th 18
```

Proposed:
```
<a name="1.0.0"></a>
## 1.0.0
Feb 28th 18
```

I've seen this done by other changelog generators and I've found it an useful feature. If this is accepted, I'll be glad to open a pull request. Thank you

**Comment by mikestead** [comment]
@engfragui great idea and yes would love this addition if you have time!

**Comment by engfragui** [comment]
Thanks @mikestead. How do you usually go about testing your changes locally?

**Comment by engfragui** [comment]
Based on our conversation on #9, I'm going to close this issue. Thank you
